# Generated by Django 4.2.16 on 2024-09-24 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Financial', 'Financial'), ('Personal Development', 'Personal Development'), ('Fitness', 'Fitness'), ('Productivity', 'Productivity')], max_length=50)),
                ('creature_type', models.CharField(choices=[('Squirrel', 'Squirrel'), ('Owl', 'Owl'), ('Fox', 'Fox'), ('Beaver', 'Beaver')], max_length=10)),
                ('target_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
