# Generated by Django 4.2.16 on 2024-09-24 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_goal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Step Date')),
                ('description', models.CharField(blank=True, choices=[('Research', 'Research'), ('Plan', 'Plan'), ('Start', 'Start'), ('Execute', 'Execute'), ('Review', 'Review'), ('Adjust', 'Adjust'), ('Collaborate', 'Collaborate'), ('Reflect', 'Reflect')], max_length=255)),
                ('custom_description', models.CharField(blank=True, max_length=255, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.goal')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
