# Generated by Django 4.2.16 on 2024-09-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='milestones',
            field=models.ManyToManyField(to='main_app.milestone'),
        ),
    ]
